name: Deploy Kiddle Dental Clinic to Azure Static Web Apps

# Trigger deployment on push to main branch
on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main, master ]

# Environment variables
env:
  APP_LOCATION: "client" # App source code path
  OUTPUT_LOCATION: "build" # Built app content directory
  NODE_VERSION: '18.x' # Node.js version to use

jobs:
  build_and_deploy_job:
    # Only run on push events or non-draft pull requests
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Kiddle Dental Clinic
    
    steps:
    - name: 🦷 Checkout Kiddle Dental Clinic Code
      uses: actions/checkout@v4
      with:
        submodules: true
        lfs: false

    - name: ⚡ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: 📦 Install Dependencies
      run: |
        cd client
        npm ci

    - name: 🔧 Build React App
      run: |
        cd client
        npm run build
      env:
        CI: false # Ignore warnings during build

    - name: 🚀 Deploy to Azure Static Web Apps
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations
        action: "upload"
        app_location: ${{ env.APP_LOCATION }}
        output_location: ${{ env.OUTPUT_LOCATION }}
        skip_app_build: true # We build manually above

  close_pull_request_job:
    # Clean up staging environment when PR is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    
    steps:
    - name: Close Pull Request
      id: closepullrequest
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        action: "close"
